#' \code{estimateEffects()} is used to estimate the effect of the
#' treatment along the entire frontier. 
#' 
#' @param frontierObject An object generated by \code{makeFrontier()}
#' 
#' @param myForm An object of class formula (or one that can be
#'     coerced to that class). This will be passed to \code{lm()} to
#'     estimate the point estimates for the causal effect estimates
#'     across the frontier.
#' 
#' @param propEstimated The proportion of points on the frontier to
#'     estimate.  By default, 100\% of the points on the frontier are
#'     estimated. To estimate less than 100\% of the points, pass the
#'     proportion to be estimated to prop.estimated (for example, .6
#'     to estimate 60\% of the points).
#'     
#' @param modDependenceFormula The formula used as the base formula
#'     for the Athey-Imbens model dependence estimates.
#'
#' @param continuousVars All continuous control variables in
#'     mod.dependence.formula must be passed as a character vector to
#'     continuous.vars. A cutpoint for each of these variables will be
#'     estimated with segmented regression.
#'     
#' @param seed The seed used before estimation of the effects. If
#'     prop.estimated is less than 1, this is necessary in order to
#'     replicate the exact plot.
#' @param modelDependenceEsts The number of points on the frontier
#'     to estimate. Note that for each point, a separate linear model
#'     must be fitted, so this can greater increase run time if too
#'     large. Defaults to 100 points.
#'     
#' @param meansAsCutpoints FALSE by default. If TRUE, cutpoints are
#'     calculated as the mean instead of the breakpoint in a segmented
#'     regression. This is sometimes much faster.
#' @param alpha 0.95 by default. Confidence interval for estimated
#'     effects.
#'
#' @examples
#' data(lalonde)
#' 
#' match.on <- colnames(lalonde)[!(colnames(lalonde) \%in\% c('re78', 'Treat'))]
#' 
#' my.frontier <-
#' matchit(as.formula("treat ~ age + educ + black + hispan"),
#' lalonde,"MahalFrontier")
#' 
#' mod.dependence.form <- as.formula("re78 ~ treat + age + black + education
#'                           + hispanic + married + nodegree + re74 + re75")
#'
#' my.estimates <- estimateEffects(my.frontier, 're78 ~ treat',
#' modDependenceFormula = mod.dependence.form,
#' continuousVars = c('age', 'education', 're74', 're75'),
#' propEstimated = .1,
#' meansAsCutpoints = TRUE)
#' 
#' @references King, Gary, Christopher Lucas, and Richard
#'   Nielsen. "The Balance-Sample 
#'   Size Frontier in Matching Methods for Causal Inference." (2015).
#' @export
estimateEffects <-
    function(frontierObject,
             myForm,
             propEstimated = 1,
             modDependenceFormula = NULL,
             continuousVars = NA,
             seed = 1,
             modelDependenceEsts = 100,
             meansAsCutpoints = TRUE,
             alpha=0.95){
        if (!requireNamespace("MatchingFrontier", quietly = TRUE))
            stop("MatchingFrontier package is required. Please install it.")
        
        effect.estimates <- MatchingFrontier::estimateEffects(frontier.object = frontierObject,
                                                              my.form = myForm,
                                                              prop.estimated = propEstimated,
                                                              mod.dependence.formula = modDependenceFormula,
                                                              continuous.vars = continuousVars,
                                                              seed = seed,
                                                              model.dependence.ests = modelDependenceEsts,
                                                              means.as.cutpoints = meansAsCutpoints,
                                                              alpha=alpha)
        class(effect.estimates) <- "frontierEstimates"
        return(effect.estimates)
    }
